id: P008186
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD90027
  title: ནན་ཕིང་རྫོང་གི་ལོ་རྒྱུས།
  author: ''
  volumes:
    9058cc166ab64fb28b19e2b2dd028a82:
      image_group_id: I1PD90100
      title: ''
      volume_number: 1
      total_pages: 1068
